package com.optimasc.definitions;

import com.optimasc.utils.AttributeSet;

/** Represents a named entity or object. 
 * 
 *  <p>An entity can represent anything, such 
 *  as a type definition, a directory entry in ITU-T X.500,
 *  a definition or schema or an actual literal definition</p>
 * 
 *  <p>An entity consists of several attributes or properties: a name
 *  that identifies, a potential unique identifier as well 
 *  as an optional description. Unless otherwise noted in the 
 *  key definitions, all attributes are represented as 
 *  {@link java.lang.String}.
 *  </p>
 *  
*  <p>The following attributes are associated with an entity:</p>
 *  
 *  <table>
 *    <tr><th>Attribute name</th><th>Mandatory</th><th>Type</th><th>Description</th></tr>
 *    <tr><td>{@link #KEY_ID}</td><td>TRUE</td><td><code>String</code></td><td>Unique identifier. If not explicitly set, automatically generated by appending {@link #KEY_ID_SUFFIX} to the qualified name.</td></tr>
 *    <tr><td>{@link #KEY_NAME}</td><td>TRUE</td><td><code>String</code></td><td>Qualified name of the entity (may include namespace prefix). Maximum length is {@link #NAME_MAX_LENGTH} characters. Must be explicitly assigned and cannot be null or empty.</td></tr>
 *    <tr><td>{@link #KEY_NAME_NS_URI}</td><td>FALSE</td><td><code>String</code></td><td>Namespace URI associated with the name (e.g., "http://example.com/schema"). If null, the entity has no namespace.</td></tr>
 *    <tr><td>{@link #KEY_OBJECT_CLASS_NAME}</td><td>FALSE</td><td><code>String</code></td><td>Object class name as defined in ITU-T X.501. Used by {@link EntityFactory} to verify mandatory attributes among others.</td></tr>
 *  </table>
 *  
 *  <p><b>Name Resolution:</b></p>
 *  <ul>
 *    <li>{@link #getName()} returns the full qualified name</li>
 *    <li>{@link #getLocalName()} returns the local part (after any namespace prefix)</li>
 *    <li>{@link #getExpandedName()} returns the namespace URI concatenated with the local name</li>
 *  </ul> *    
 * 
 * @author Carl Eric Codere
 *
 */
public interface Entity extends AttributeSet
{
  
    /**
     * Maximum length of the name attribute in characters. This is 
     * specified in IETFC RFC 4520 - Object identifier descriptors.
     */
    public static final int NAME_MAX_LENGTH = 48;
    

    /**
     * Key for the name associated to this named entity. This is equivalent to
     * LDAP-NAME in ITU-T X.501. This value is mandatory and represents a descriptor.
     * In case the name is namespace aware, this is the qualified name.
     */
    public static final String KEY_NAME = "commonName";
    
    
    /**
     * Key for the name namespace URI associated to this named entity. 
     * This value is optional. 
     */
    public static final String KEY_NAME_NS_URI = "NAME_NS";
    
    /** Key for the Object class attribute associated with this named entity. 
     *  This is the same definition as specified in ITU-T X.501.
     * 
     */
    public static final String KEY_OBJECT_CLASS_NAME = "objectClass";
    
   
   /**
    * Unique identifier associated to this named entity. This is equivalent to
    * ID in ITU-T X.501. This value should be OBJECT IDENTIFIER format 
    * in dotted decimal notation (e.g., '1.2.3.4') 
    * OR end with {@link #KEY_ID_SUFFIX} if auto-generated, but
    * other values are allowed."
    */
   public static final String KEY_ID = "Object Identifier";
   
   /** The qualified name appended with this string represents
    *  the Unique Identifier if it is not explicitly set. 
    */
   static final String KEY_ID_SUFFIX = "-OID";
   
   
   
   /** Returns the local part of the named entity.
    *  The local part is the part after the 
    *  namespace prefix or the entire name if no 
    *  namespace exists.
    * 
    * @return A non-null value for this entity.
    */
   public String getLocalName();

   /** Returns the namespace URI of this
    *  named entity. 
    * 
    * @return A potentially <code>null</code> value
    *  of the namespace URI
    */
   public String getNamespaceURI();
   
   
   
   /** Returns the qualified name of this named
    *  entity.
    * 
    * @return A non-null value for this 
    *  named object.
    */
   public String getName();
   
   
   /** Returns the expanded name of this named entity using RDF expanded 
    *  name syntax, i.e., the namespace URI concatenated with the local name.
    *  If no namespace URI is present, returns just the local name.
    * 
    * @return A non-null value representing the expanded name.
    */
   public String getExpandedName();
   
   
   /** Returns the unique identifier associated with this named entity.
    *  This is usually an OBJECT IDENTIFIER.
    * 
    * @return A non-null value.
    */
   public String getID();   
   
   /** Returns the object class of this entity.
    * 
    * @return The associated object class with this
    *   entity or <code>null</code> if not specified.
    */
   public String getObjectClass();
   
   
}
